# Project information
site_name: WINGMAN Documentation
site_description: Comprehensive documentation for WINGMAN - Your Security Context Platform
site_author: PeakDefence
# site_url will be automatically set by GitHub Pages

# Repository
repo_name: PeakDefence/wingman-docs
repo_url: https://github.com/PeakDefence/wingman-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 PeakDefence

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: material/shield-account
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.png
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - macros:
      include_dir: docs/
      include_yaml: 
        - '**/*.yaml'
        - '**/*.yml'
      j2_block_start_string: '{%'
      j2_block_end_string: '%}'
      j2_variable_start_string: '{{'
      j2_variable_end_string: '}}'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - glossary:
      file: glossary.md

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: getting-started/welcome.md
    - Quick Start Guide: getting-started/quick-start.md
    - WINGMAN Overview: getting-started/overview.md
  - Core Concepts:
    - Graph Database Model: core-concepts/graph-database.md
    - Data Model: core-concepts/data-model.md
    - Node Types: core-concepts/node-types.md
    - Node Relationships: core-concepts/relationships.md
    - Flows: core-concepts/understanding-flows.md
  - Setting Up WINGMAN:
    - Basic configuration: setup/setup-overview.md
    - Initial Data Import: setup/data-import.md
    - Node Customization: setup/node-configuration.md    
    - Company context (example): setup/company-context.md
  - Using WINGMAN:
    - User Interface: usage/ui-guide.md
    - Chat Functionality: usage/chat.md    
    - Node Management: usage/node-management.md    
    - Relationship Management: usage/relationship-management.md    
  - Integration Management:
    - Integration Types: integrations/overview.md
    - Communication Integrations: integrations/communication.md
    - Pen-test tools Integration: integrations/pen-test-tools.md    
    - MCP Connector: integrations/mcp-connector.md
    - Jira Integration: integrations/jira.md
  - Use Cases:
    - Asset Registry: use-cases/asset-registry.md
    - Policy & Procedure Management: use-cases/policy-procedure-management.md
    - Requirements documentation: use-cases/requirements-documentation.md
    - Risk Management: use-cases/risk-management.md
    - Vulnerability Management: use-cases/vulnerability-management.md
    - Incident Response: use-cases/incident-response.md
    - Compliance and Audit: use-cases/compliance-audit.md
  - Glossary: glossary.md

# Extra
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PeakDefence/wingman-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PeakDefence

# Build
strict: true
use_directory_urls: true

# Customization
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

# Exclude files
exclude_docs: |
  /.*
  /README.md
  /LICENSE
  /mkdocs.yml
  /requirements*.txt
  /overrides/
  /docs_src/
  /site/
  /.github/
  /.gitignore
  /.git/
  /venv/
  /env/
  /.venv/
  /node_modules/
