name: Deploy WINGMAN Documentation to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Environment variables
env:
  DEPLOY_BRANCH: gh-pages
  COMMIT_MSG: "Deployed ${{ github.sha }}"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Set the permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build documentation
        run: mkdocs build --strict --verbose --site-dir ./site
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          branch: ${{ env.DEPLOY_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          clean-exclude: |
            .git
            .gitignore
            .nojekyll
          commit-message: ${{ env.COMMIT_MSG }}
          force: true
