name: Deploy WINGMAN Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Environment variables
env:
  DEPLOY_BRANCH: gh-pages
  COMMIT_MSG: "Deployed ${{ github.sha }}"

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    # Only run on pushes to main/master or on workflow_dispatch
    if: github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # If you're using a personal access token for deployment
          token: ${{ secrets.GH_TOKEN || github.token }}
          # This is necessary for the GitHub Pages action to work properly
          persist-credentials: false
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build documentation
        run: mkdocs build --strict --verbose --site-dir ./site
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ env.DEPLOY_BRANCH }}
          folder: site
          clean: true
          clean-exclude: |
            .git
            .gitignore
            .nojekyll
            CNAME
          commit-message: ${{ env.COMMIT_MSG }}
          force: true
          
  deploy-to-peakdefence:
    name: Deploy to docs.peakdefence.com
    needs: deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build documentation
        run: mkdocs build --strict --verbose --site-dir ./site
        
      - name: Deploy to docs.peakdefence.com
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "site/*"
          target: ${{ secrets.DEPLOY_PATH || '/var/www/docs.peakdefence.com' }}
          strip_components: 1
          rm: true
