name: Setup GitHub Actions

on:
  workflow_dispatch:
  push:
    branches: [ setup-actions ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./
