name: Sync

on:
  push:
    branches:
      - "**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # https://github.com/offensive-vk/auto-repo-sync
      - uses: offensive-vk/auto-repo-sync@v8
        with:
          target-url: https://gitlab.com/peakdefence/wingman/docs.git
          # This access tokens from GitLab
          target-username: ${{ secrets.TARGET_USERNAME }}
          target-token: ${{ secrets.TARGET_TOKEN }}
