name: Sync

on:
  push:
    branches:
      - "**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: offensive-vk/auto-repo-sync@v8
        with:
          target-url: git@gitlab.com:peakdefence/wingman/docs.git
          target-username: ${{ secrets.TARGET_USERNAME }}
          target-token: ${{ secrets.TARGET_TOKEN }}
